language: php
php:
  - '7.3'

before_install:
  - nvm install lts/*

install:
  - yarn install
  - yarn prod
  - composer install

script:
  - vendor/bin/phpunit --coverage-html reports/
  - bash <(curl -s https://codecov.io/bash)
